import { motion } from "framer-motion";
import { useEffect, useState } from "react";

interface Props {
  outcome: "win" | "lose" | "draw";
  moves: number;
  profile: string[];
  onAgain: () => void;
}

export function EndScreen({ outcome, moves, profile, onAgain }: Props) {
  const [reveal, setReveal] = useState(0);
  useEffect(() => {
    const id = window.setInterval(() => setReveal((r) => r + 1), 700);
    return () => window.clearInterval(id);
  }, []);

  const verdict =
    outcome === "win"
      ? "SUBJECT PREVAILED"
      : outcome === "lose"
      ? "SUBJECT TERMINATED"
      : "INCONCLUSIVE";

  return (
    <div className="min-h-screen w-full flex items-center justify-center p-6">
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        className="w-full max-w-2xl border border-blood/70 box-glow-red bg-background/90 p-8 font-mono"
      >
        <div className="text-xs text-muted-foreground mb-2">
          /void/sessions/{Date.now().toString(36)}.log
        </div>
        <div
          className="text-3xl md:text-4xl rgb-split mb-1"
          style={{ color: "var(--blood)" }}
        >
          ░ PSYCHOLOGICAL PROFILE ░
        </div>
        <div className="text-sm text-muted-foreground mb-6">
          generated by chess.exe // {moves} moves observed
        </div>

        <div
          className="text-xl mb-6 text-glow-red"
          style={{ color: "var(--blood)" }}
        >
          {verdict}
        </div>

        <ul className="space-y-2">
          {profile.map((p, i) => (
            <motion.li
              key={i}
              initial={{ opacity: 0, x: -8 }}
              animate={reveal > i ? { opacity: 1, x: 0 } : {}}
              className="text-glow"
              style={{ color: "var(--terminal)" }}
            >
              ▸ {p}
            </motion.li>
          ))}
        </ul>

        <div className="mt-8 flex flex-wrap gap-3 items-center justify-between">
          <div className="text-xs text-muted-foreground flicker">
            file saved to your machine. you cannot delete it.
          </div>
          <button
            onClick={onAgain}
            className="px-5 py-2 border border-terminal/70 box-glow text-glow hover:bg-terminal/10 transition-colors"
            style={{ color: "var(--terminal)" }}
          >
            ▶ play again
          </button>
        </div>
      </motion.div>
    </div>
  );
}
